title: River Valley Christian Fellowship
description: We are a group of believers saved by grace though faith in Christ and His finished work (Eph. 2:8-9) who meet simply around the Lord Jesus, seeking to follow only the directions given in the New Testament. Currently we are a small group, meeting in the Senior Citizen Center in Chippewa Falls, Wisconsin (Chippewa Falls is a small town bordering Eau Claire).
show_downloads: true
google_analytics:
theme: 
headers: head.html