<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html>
<head>
<?php include("inc/meta.inc.php"); ?>

    <title>Is the Bible Real?</title>
</head>

<?php include("inc/header.inc.php");
      include("inc/textBox1.inc.php"); ?>

<h1>WHAT MAKES THE BIBLE REAL?</h1>
                                                         <br />


<p><img src="img/scroll.gif" width="102" height="83" align="Right" border="0"><br /><br />
There are several different answers to this question but the one I will explore is prophecy.  What is prophecy?  Webster's definition: an inspired utterance of a prophet/ prediction.  So it's a foretelling of an event given by God through an individual.  Sounds a little crazy doesn't it?  After all, lots of people claim to hear from God, Mormon-Mormonism, Muhammad-Islam, and Charles Russell-Jehovah Witnesses.  Let me give you some brief information on these groups.  They all:
<ol type="A">
<li> Believe there is one god, </li><li> Believe the Bible, some believing more parts of it than others, </li><li> Believe the book(s) their founders wrote while claiming to be hearing from this one god.</li>
</ol>
  So if there is only one god, and they have all heard from him, then their books and the Bible should all give the same message and be in perfect agreement right?  The only thing is, they don't.  In fact, they aren't even close.
<p>Another fact I would like to point out is the Bible was completed hundreds of years before any of these and many other beliefs came into existence.  The last chapter of the Bible states: <b class="bible">Rev. 22:18 "For I testify to everyone who hears the words of the prophecy of this book: If anyone adds to these things, God will add to him the plagues that are written in this book; and if anyone takes away from the words of the book of this prophecy, God shall take away his part from the Book of Life, from the holy city, and from the things which are written in this book."</b>  I wonder if Muhammad and these other so-called prophets ever read these verses?  With that in mind, why would this one god complete one book and then, give completely different prophecy to different people?  Wouldn't that cause a lot of confusion, arguing, dissension and even wars? Isn't that exactly what we see happening?   Who was it that attacked us on 9-11 declaring it a "holy war"?  What's all the fighting going on in the Middle East about?  What about all the arguments on issues in our own country?  I don't believe the one true righteous God would ever send that kind of confusion because His word says so.  <b class="bible">I Cor. 14:33 "For God is not the author of confusion but of peace, as in all the churches of the saints."</b>
<p>We can know true prophecy from false.  For example, if someone came to you and said, "In one month from now you will have a new job and be living in a different town."  One month passes and everything that person told you came to pass.  Again, the person comes and says; "One month from now you will be given a promotion at work."  Would you believe them?  Good chance of it.  God worked in a similar fashion in giving us His inspired word.  He spoke through men to men.  We know if it is of God by whether or not it comes to pass and if it keeps us directed toward the one true God (if it aligns with His word).  New prophecy never contradicted old prophecy.  The Bible gives these two criteria.
<ol type="1">
<li><b class="bible">Duet. 18:21 "And if you say in your heart, 'How shall we know the word which the LORD has not spoken?'-when a prophet speaks in the name of the LORD, if the thing does not happen or come to pass, that is the thing which the LORD has not spoken;"</b>
<li><b class="bible">Deut 13:1 "If there arises among you a prophet or a dreamer of dreams, and he gives you a sign or a wonder, and the sign or the wonder comes to pass, of which he spoke to you, saying, 'Let us go after other gods'-which you have not known-'and let us serve them,' you shall not listen to the words of that prophet or that dreamer of dreams, for the LORD your God is testing you to know whether you love the LORD your God with all your heart and with all your soul."</b>
</ol>  Now more than ever, there is a lot of people seeking signs and wonders but the signs and wonders don't line up with God's word.  People are calling upon psychics, sorcerers, palm readers, mediums (communicators of the dead) to find out their future and life after death. All claiming that it is of God and some of them even quote from the Bible.  I wonder if they've read these verses, <b class="bible">Lev. 19:31 "Give no regard to mediums and familiar spirits; do not seek after them, to be defiled by them: I am the LORD your God."</b>  <b class="bible">Matt 16:4 <span class="bibleRed">"A wicked and adulterous generation seeks after a sign…"</span></b>  How convenient to pick and choose what parts you do and don't want to believe.  Either you believe all of God's word or none of it.
<p>Another aspect of true prophecy is witnesses.  God spoke through over 50 individuals over a period of approximately 1500 years in completing His word.  The Book of Mormon, Qur'an etc. only have one witness, being the author himself.  Again, how convenient.  Imagine for a moment a man being accused of a crime by another individual.  It would be hard to convince a jury with only one man's word against another.  But imagine if there were 100 people testifying against the man.  That would be a testimony.  God says this in His word.  <b class="bible">Deut. 19:15 "One witness shall not rise against a man concerning any iniquity or any sin that he commits; by the mouth of two or three witnesses the matter shall be established."</b>  God gave us His word by many witnesses and over a long period of time to show that there is no way it could be made up.  He knows our hearts and how critical we can be; He created us.  He isn't going to feed us a line of garbage and expect us to believe it without backing it up.  Jesus told the people many things that would come to pass.  A lot was about Him and was fulfilled but some of it is happening right now while others are still to come.  The reason, <b class="bible">John 14:29 <span class="bibleRed">"And now I have told you before it comes, that when it does come to pass, you may believe."</span></b>
<p>I will leave you with these thoughts and questions: If the Bible isn't real, why do people say Jesus Christ name in vain instead of Allah, Buddha etc.?  Why was our nation founded on it?  Why is our calendar based on it?  How could the authors who didn't even live in the same life-span prophesy of the same event(s) with 100% accuracy?  Meteorologists with all man's technology can't predict weather of tomorrow with that precision.  God tells us in His word everything we could possibly need to know.  It's not a book of stories or a moral code to live your life by.  It's a factual record of events from creation to present to the future.  Above all, it is uniquely knit together because although many men wrote it over a long period of time, every part of it points to the Lord Jesus Christ.  Most of which was written before He was even born.  Proving there is one Author inspiring many witnesses to complete unity as a tremendous testimony.
<p>God tells us how our sins can be forgiven through His Son.  When your life here is over and you are standing before God for judgment, how important will your job, house, what kind of car you drove, clothes you wore, or how much money you had be to you at that moment?  And what will you say when He asks you why He should let you into heaven?  Because you were a good person, or you weren't as bad or any different than someone else?  Because you went to church, went to confirmation, or were baptized?  The Bible makes it very clear it won't be for any of these reasons.  But we'll talk about this in the future.

<?php include("inc/textBox2.inc.php");
      include("inc/footer.inc.php"); ?>

</body>
</html>