<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html>
<head>
<?php include("inc/meta.inc.php"); ?>

    <title>What Went Wrong?</title>
</head>

<?php include("inc/header.inc.php");
      include("inc/textBox1.inc.php"); ?>

<h1>WHAT WENT WRONG?</h1>

<br />

<p><img src="img/scroll.gif" width="102" height="83" align="Right" border="0"><br /><br />

Last time, I talked about characteristics of God leaving off with the fact that He is our judge.  I then stated that we need to understand how He sees us before we'll understand His love.  So let's go to the beginning.
<p>
<b class="bible">Gen. 1:27 "So God created man in His own image, in the image of God He created him; male and female He created them.</b>  "Image" in the original Hebrew language means: shade. This doesn't mean that man necessarily looks like God, but rather that man would be a representative, not the real thing but a "shadow" of God.
<p>
God gave man a place to live (earth) filled with life, and gave him charge over it.  <b class="bible">Vs. 28 "Then God blessed them, and God said to them, "Be fruitful and multiply; fill the earth and subdue it; have dominion over the fish of the sea, over the birds of the air, and over every living thing that moves on the earth."</b>  Notice that man isn't placed on the same plane as the animals like we were taught in school (evolution).  The animals weren't created in God's image.  We are of much more value than they are.
<p>
Moving right along, <b class="bible">Gen. 2:15 "Then the LORD God took the man and put him in the garden of Eden to tend and keep it.  And the LORD God commanded the man, saying, "Of every tree of the garden you may freely eat; but of the tree of the knowledge of good and evil you shall not eat, for in the day that you eat of it you shall surely die."</b>  Life in the garden was perfect because God, Adam, and Eve had fellowship.  The Lord supplied them with everything they needed, most importantly His word.  You see, when the Lord told them not to eat of the one tree, it wasn't to slap a restriction on them. It was for their protection, because He loved them.  He also loved them enough when He created them to give them, and us, a free will.  He doesn't program us to love Him.  After all, love isn't genuine if there is no other option.
<p>
You have probably been told of this account at least a dozen times in your life and know what their decision was. <b class="bible">Gen. 3:1-7 "Now the serpent was more cunning than any beast of the field which the LORD God had made.  And he said to the woman, "Has God indeed said, 'You shall not eat of every tree of the garden'?"  And the woman said to the serpent, "We may eat the fruit of the trees of the garden; but of the fruit of the tree which is in the midst of the garden, God has said, 'You shall not eat it, nor shall you touch it, lest you die.'"  Then the serpent said to the woman, "You will not surely die, For God knows that in the day you eat of it your eyes will be opened, and you will be like God, knowing good and evil."  So when the woman saw that the tree was good for food, that it was pleasant to the eyes, and a tree desirable to make one wise, she took of its fruit and ate.  She also gave to her husband with her, and he ate.  Then the eyes of both of them were opened, and they knew that they were naked; and they sewed fig leaves together and made themselves coverings."</b>  We learn a lot from these verses.  The serpent (Satan) came to Eve and asked a question about what God had said (His word).  Eve then replied with what God had said, but not accurately.  She added <b class="bible">"nor shall you touch it"</b>.  Satan then tells her a flat out lie <b class="bible">vs.4 "You will not surely die"</b>.  So Eve, not heeding God's word (sin), believed the lie, fulfilled the lust of the flesh <b class="bible">vs.6 "that it was pleasant to the eyes"</b> and ate of the tree with her husband.
<p>
Just like that sin entered the human race through one man's disobedience.  <b class="bible">Rom.5:12 "Therefore, just as through one man sin entered the world, and death through sin, and thus death spread to all men, because all sinned."</b>  And we know that guilt came immediately because they tried to cover their shame <b class="bible">vs.7 "they sewed fig leaves together and made themselves coverings."</b>
<p>
God is not slack concerning His word because God is not a liar.  He told them that the consequence for eating of the tree would be death.  Not only physical death, but more severe, spiritual death (eternal separation from God).  Fellowship was broken.  The Lord now begins to reveal to them the consequences of their decision.  In Gen. 3:14-19 is a list of some of these, which includes pain in childbirth and the ground being cursed.  It would now bring forth weeds and thistles causing toil and hard work to eat of it.  There is no mention of sickness, or diseases (human or animal) before this point.  Sin carries great consequences.  But God is also not slack in mercy, for middle of all the curses pronounced upon the serpent, woman, and man He gives a great promise.  He tells the serpent, <b class="bible">Gen.3:15 "And I will put enmity between you and the woman, and between your seed and her Seed; He shall bruise your head, and you shall bruise His heel."</b>  Since sin entered the world through man, God would redeem man by becoming a Man (<b class="bible">her Seed</b>).  The Man (Jesus) would be the One who would <b class="bible">bruise</b> Satan's <b class="bible">head</b>, picturing a fatal blow that gives complete victory over the consequence of sin (death or hell), despite that Satan would <b class="bibile">bruise His heel</b> (the sufferings of the cross.)  You see God was telling of the plan of redemption.  Man sinned against God but God wishes to <u>AND PROVIDES</u> the way to restore fellowship between Himself and sinful man.  This is shown in the picture of His plan that the Lord gives immediately following the curses.  <b class="bible">Gen.3:21 "Also for Adam and his wife the LORD God made tunics of skin, and clothed them."</b>  Their attempt (<b class="bible">fig leaves</b>) to cover up their shame (sin) couldn't work, because the cost or payment for sin is death, not works (<b class="bible">fig leaves</b>).   God out of His mercy clothed them, but in order to make those <b class="bible">skins</b> (of animals) it meant bloodshed.  Innocent life was given for guilty life.

These Old Testament (BC) examples are pictures of the Lord Jesus (New Testament, AD).  God eventually provided the ultimate bloodshed for sins: Jesus.  Maybe you don't totally understand or see the picture yet.  But stay with me in these letters and I will show you from God's Word (not mine) that you can know that you will go to heaven when you die.  What is more important than that?  It's also important to know right now because you don't know when you'll breathe your last breath.  It's amazing how we think we have so much time to "get right with God".  Would you be more interested in your eternal future if you knew you would die today?  What makes you think you won't?  Have you ever put yourself in Adam and Eves shoes?  Do you know that Satan still comes to see if you know God's word?  If you don't read His word, how can you know it?  If you don't know His word how many lies are you believing just like Eve did?  How many good deeds (fig leaves) are you trying to do in hopes of covering up your sins and clearing your guilt?  Remember that God provided a way to restore fellowship with Adam and Eve and the same is true for us today.  Our works are of no avail (<a href="http://www.biblegateway.com/cgi-bin/bible?passage=Ephesians+2:8&version=NKJV" target="_blank" class="plainLink">Eph.2:8</a>).   Next time we will look at specific sins by focusing on the Ten Commandments.  We will then see how we will stack up against what God will judge us with.  <b class="bible">Ps.96:13 "For He is coming, for He is coming to judge the earth."</b>

<?php include("inc/textBox2.inc.php");
      include("inc/footer.inc.php"); ?>

</body>
</html>