<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html>
<head>
<?php include("inc/meta.inc.php"); ?>
<?php include("inc/davidmeta.inc.php"); ?>

    <title>River Valley Christian Fellowship Updates on David</title>
</head>

<?php include("inc/header.inc.php"); ?>

<table width="100%" border="0" cellspacing="5" class="boxText">
<tr>
    <td colspan="2" align="left">

    <title>Update Page for David Hanson - December 2013</title>

<p> <b>2014 </b>

</p>



<p>1/2/14 (Rachel Hanson) David is becoming more confident with talking and is doing more and more verbally. It is still hard to understand him a lot but every day, his pronunciation and volume make little strides. He amazed me last night by "singing" 3 complete songs to me! I put singing in quotations because his singing isn't real melodious yet...it's more of a "joyful noise"  I could understand almost every single word in the first song. It was incredible. Just a couple months ago, he was needing lots of prompting to even get "Happy Birthday" out. It thrills my soul to hear him calling out hymns in breaking of bread and then joining in singing. It's so neat to see specific prayers being answered one at a time. It's like watching a caterpillar morph into a butterfly...it's an amazing journey God has put us on. And like the butterfly emerging from the cocoon, it has it's not-so-glorious, painful moments as well.
David is completely off gabapentin now. I don't want to be dogmatic about this because I'm not a doctor or anything, but I think he is experiencing withdrawal symptoms. In my small amount of research, it seems that one can have a biotin (B vitamin) deficiency as a result of being on gabapentin for an extended period of time. Since quitting gabapentin, he is experienced extreme itchiness, choking sensation, restless legs and other things that seem to point toward a biotin deficiency. The itchiness is incredibly intolerable and along with choking more on his saliva, it makes it difficult for him to sleep. It makes it difficult for me to sleep too! I am experimenting with adding Brewer's yeast into his diet to supplement with more B vitamins.
We are really looking forward to getting rid of the g-tube soon. David is totally eating/drinking by mouth and I'm incorporating more texture into his foods so he's mostly on a mechanical soft diet now. Because of the way the treadmill harness system is set up, he cannot work on walking on the treadmill until it's out!

<p> 1/13/14 (Rachel Hanson) David is becoming increasingly more clear with speech. We've noticed a drastic change in the last two weeks. His speech therapist is working with him on longer sentences and is starting to work on cognitive issues that are coming to the surface as his speech improves. 

Last Friday, David got his g-tube removed! We all (the caregiver, David, Jocelyn and I) had fevers and colds that day...otherwise we would have been much more excited!  On Christmas day, Jocelyn had tried to remove it herself but was unsuccessful and caused Daddy some stomach pain instead. So when the doctor took it out skillfully, David commented that he did a much better job than Jocelyn! I guess Jocelyn is fired.  Sometimes I get nervous about David having another seizure and setting him back again but then God reminds me He is in control.

I've been encouraged by a story of two monks lately:

"'I need oil,' said an ancient monk, so he planted an olive sapling. 'Lord,' he prayed, 'it needs rain that its tender roots may drink and swell. Send gentle showers.' And the Lord sent gentle showers. 'Lord,' prayed the monk, 'my tree needs sun. Send sun, I pray thee.' And the sun shone, gilding the dripping clouds. 'Now frost, my Lord, to brace its tissues,' cried the monk. And behold, the little tree stood sparkling with frost, but at evening it died.
Then the monk sought the cell of a brother monk, and told his strange experience. 'I, too, planted a little tree,' he said, 'and see! It thrives well. But I entrust my tree to its God. He who made it knows better what it needs than a man like me. I laid no condition. I fixed not ways or means. 'Lord, send what it needs,' I prayed, 'storm or sunshine, wind rain, or frost. Thou hast made it and Thou dost know.'" --Streams in the Desert

David gets to try crawling on the treadmill tomorrow! 

Pray for contentment for David and I. We have so much, so much to be thankful for, so many riches (material, non-material, and spiritual). Why are our eyes so swift to look down when we have so much??</p>

<p> 1/23/14 (Rachel Hanson)David's cognitive progress is coming along by leaps and bounds! It's really amazing to watch.  I've probably said this before but it's like watching a caterpillar emerge from its cocoon, transformed into a beautiful butterfly! It's not like everything is perfect or that life isn't hard still but David is doing so much better. His recovery seems to be speeding up, at least in the cognitive realm. For the last few months (at least 6 months), he's been in a stage that's typical frontal lobe damage symptoms. But recently, he's been regaining more control over impulsive, inappropriate behavior/words. We've come up with a sign that works pretty good when his brain is telling him to spit out stuff without a filter.  So instead of blurting out something embarrassing, he shows me he's biting his tongue.  It may sound silly, but it works. David is also progressing rapidly in "executive functions". In layman's terms, this means: "Being able to focus, hold, and work with information in mind, filter distractions, and switch gears is like having an air traffic control system at a busy airport to manage the arrivals and departures of dozens of planes on multiple runways. In the brain, this air traffic control mechanism is called executive functioning, a group of skills that helps us to focus on multiple streams of information at the same time, and revise plans as necessary." --- http://developingchild.harvard.edu/resources/multimedia/videos/inbrief_series/inbrief_executive_function/
David has initiated organizing a Bible Study and wants to start door-to-door evangelism outreach too. (This idea may have to wait until spring...) This is the old David! To be able to put all the things together to do these things, is nothing short of incredible. The speech therapist and neurologist acknowledge, in their mostly godless semantics, that David has "a special inner strength" and has exceeded prognostic expectations. We know his inner strength is from the Lord. "I can do ALL things through Christ which strengtheneth me." Philippians 4:13
Today was an "off day" where we had no therapy or doctor's appointments so we had a rush-free morning. The speech therapist wants David to start helping me with meal-planning, grocery lists, etc... so I decided to take it to the next level and have him plan his breakfast and direct/help me make it. He used to work at Burger King, so he wanted a croissant-wich, hash browns and coffee. We didn't have croissants so we improvised with refrigerated biscuits. He was able to do about 85% of the "bossing" accurately and helped me cut the biscuit, slather some mayo on, cut cheese, and assemble it. He was very happy with his breakfast this morning and he just glowed because I think it made him feel rather accomplished to be helping me. He was able to read Jocelyn a story last night and was able to choose appropriate ways to soothe her when she was crying. You have no idea what this does to my soul to have my husband starting to begin to be involved actively in our lives again. 
David's physical recovery has been slower but maybe his brain can only focus on one part of recovery at a time. Yesterday they had about 5 or 6 therapists assisting him in an overhead harness system to take about 50 steps. It was great but he was exhausted! 
Thank you all for praying continually for us, even after over a year and all your notes/ words of encouragement. We do feel borne up on the everlasting arms sometimes, carrying us up above our struggles, beyond human strength and joy.</p>

<p> 2/10/14(Rachel Hanson)
"...I am come that they might have life, and that they might have it more abundantly." John 10:10

ABUNDANT life... 

I remember when David was just a few days into his journey after his accident. He was still in a coma, still on total life support, still showing signs of the most severe kind of brain injury...I prayed that if God would give David life, that he would have a quality life and not be stuck inside a body and brain that didn't work. Not just "life", a few electrical impulses in the brain maintaining a status just above clinical brain death, but abundant life, a life that could be shared with others, a life that could be enjoyed, a testimony of healing. 
Sometimes it doesn't FEEL abundant. It doesn't feel like we're free to enjoy life like we used to. But we are so grateful for the quality of life the Lord has given David. I think we like to think that abundant life would mean that we are free from the burdens of health problems, financial problems, all that this creation groans under but Jesus has promised us abundant life. How can we find abundance in what seems to be a lack? 
David and I were reading in Matthew 19 about the young man who had kept all the commandments and had many possessions but he just couldn't let go of his possessions for the poor, to advance the kingdom of God. As I looked up "possessions" in the Bible, it seems to have a connection with the thought of multiplying or reproducing. A Jewish man was known as a wealthy man if he had an abundance of livestock. The Jews sought after material goods as a sign of God's blessing on them. But we, as Christians, should be seeking spiritual blessing, our eyes fixed above, our life wrapped up in the advancement of the kingdom of God for His gain and glory. We have been invited to His banqueting Table, invited to share in His joy, look for "that blessed hope". We have so much in Christ if we just LOOK UP! 
David is getting "kicked out" of occupational and speech therapies this week. It doesn't seem fair. He has been doing great and making progress. There's so much more to do. It's scary to be let out of therapy for the first time in a year and a half. We're on our own. We have to figure out how to fill David's life. How do we live "normal" again? How do we integrate back into the world? I've been looking into different options to try to keep David's progress going. Some options are working out together at the YMCA, starting equine therapy, starting training with a service dog, getting out to do more door to door in the spring... To say the least, we feel a little unprepared to jump into real life again. David wants to text and email and register for a college class...normal stuff. We're working on it but when is the rest of the world going to accept David back? When can we feel like we're a part of the community again?
</p>

<p> 3/8/14 (Annette Hanson) Such a blessing to hear David pray publicly Wednesday night, for the first time since his accident. We had to listen very carefully, but he was definitely understandable! His prayer included thanking the Lord for "another day of life" and for "every gift He gives." He also prayed that we would always be in the center of the Lord's will. As he was ready to pray, he reached out to hold his brother's hand. (I'm thinking he is used to holding Rachel's hand when they pray together, but she was away that evening) 

David's physical progress is slow, but he is maintaining a desire to keep exercising. We do keep seeing progress in his brain recovery, with more memories coming back from the time he spent in California before the accident. He was recalling friends and family involved in buying a ring for Rachel and more friends who came to visit him while in rehab. He told me about a group of children who came to visit and sang with a guitar. He was a little confused about where they were from, but it is still encouraging to see him remember "new" things that are from his more recent past.

As a mother, it touches my heart each time David says, "Hello Ma'am," takes my hand, kisses it, and tells me he loves me. A year ago, he was unable to do any of these things, and we are so grateful to the Lord, the Master Physician!</p>

<p> 3/16/14 (Rachel Hanson)
Thanks to Nathan and Ashley and our caregivers, I was able to have a vacation for a week and see some of my family and friends. This was a much needed break. I came back very refreshed despite a cold Jocelyn and I picked up and was ready to go at it again. These breaks give me the emotional energy to go back at it again with a renewed spirit and to be a better wife.
David has been free of traditional therapy for a few weeks now. He is riding a horse named "Sterling" once a week and is loving it! He has two "side walkers" that walk on either side of the horse to help support David, as his trunk control still needs help. We try to go to the YMCA 3 times a week, although it's been spotty lately due to various reasons. We've gotten David in the pool twice which he also really enjoys. It is a great experience because his body is deweighted because of the buoyant property of the water so he can relax and practice movements he might not otherwise be able to do in normal situations. He is using a regular wheelchair most of the time at home now and can propel himself around the house using his right leg.
David is holding more and more normal conversations with people although his speech still is a little unclear at times. We are getting ready to sell David's "bachelor pad" and I have been updating David on the details as we progress in the process. He has been surprising me by reminding me to do certain things. This is helpful because I have a lot of things I try to keep track of in my brain!  David has been asked to do a presentation to a group of Electrical Power Distribution and Diesel Mechanic students at the technical college David attended in about a month. We would appreciate prayer in this matter as it is an opportunity to share David's testimony and faith in Christ as well as educate them in safety in the field. 
Last Wednesday, we had the opportunity to spend a few hours with an expert rehabilitation engineer that brought some cool "toys" for David to try. From her assessment, it looks like she will be very helpful in providing us with some assistive technology for communication, computer/ipad and cell phone use.
We also attended a doctor's appointment last week with David's physical medicine and rehabilitation doctor. He made a referral to get a second opinion on David's eyes/vision. I need to do some research on neurological ophthalmologists in the area and would appreciate prayer for wisdom and direction in this. I would love to see if David's vision could be improved somehow. Although no one has definitely come out and said it, it has been alluded to that cranial nerve damage is the cause for his vision deficits. The doctor is also going to do some botox injections in his hamstrings in a couple weeks. I'm hoping this will help relax those muscles so standing and practicing walking in his "Tram" is possible and easier.
Thank you again for your consistent prayers for us. <br> I share this to show how David's piano playing has progressed. He is now able to use all his fingers on his right hand instead of just one finger and is starting to try some simple chords. This is amazing because he really doesn't practice all that often!


<div id="fb-root"></div> <script>(function(d, s, id) { var js, fjs = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) return; js = d.createElement(s); js.id = id; js.src = "//connect.facebook.net/en_US/all.js#xfbml=1"; fjs.parentNode.insertBefore(js, fjs); }(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-post" data-href="https://www.facebook.com/photo.php?v=10151917630121193" data-width="466"><div class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/photo.php?v=10151917630121193">Post</a> by <a href="https://www.facebook.com/rachel.hanson86">Rachel Hanson</a>.</div></div>

</p>

<p> 3/19/14 (Rachel Hanson)A friend of ours was in a bad car accident a few days ago and is a similar condition to David after his accident. My heart is heavy but I am so glad we have a compassionate God who hears our petitions. The Lord showed me these verses recently and they are an encouragement to me especially in this time. It gives hope in the midst of suffering, a reason to carry on: "For I consider that the sufferings of this present time are not worthy to be compared with the glory which shall be revealed in us. For the earnest expectation of the creation eagerly waits for the revealing of the sons of God. For the creation was subjected to futility, not willingly, but because of Him who subjected it in hope; because the creation itself also will be delivered from the bondage of corruption into the glorious liberty of the children of God." Romans 8:18-21</p>

<p 3/30/14 (Rachel Hanson) The changes in David are becoming slower and slower although still perceptible. He bravely endured 8 Botox injections into both hamstring muscle groups in his legs. We are hoping this helps the horrible spasms he gets when trying to stand up and make it possible for him to improve his standing balance to a point where he can begin training to walk again. The doctor wants him to return to physical therapy. I am very happy about this because I am doing my best to get him to the gym/pool 3 times a week and have care givers do exercises and range of motion daily, but it is wearing on me and inconsistent because of inconsistent care givers. Even though I may have the skills for helping David, I really am not the best option for being his therapist. He gets rather distracted and it's not very productive. lol  And after all, I'm an orthopedic therapist who is used to getting results in one visit, not weeks or months or perhaps years! God is teaching me patience. I'm not a very good student in this area of life though because He patiently sees me flunk over and over. 
We were reminded last night of the story behind the hymn "It is Well With my Soul". The man who wrote the song had gone through losing his home to a fire and his children in a ship sinking in the ocean. But what a hope we have to be able to say, "It is WELL with my soul!" With the perspective of eternity in mind, it's easier to get through the daily grind of the frustration of living with severe disability. I want to learn how His strength is made perfect in my weakness, David's weakness.
He is having more pain lately. Pain complicates things. Not that he doesn't have enough complications. He wants to stand more, change position in bed at night more, and awakens at night more. So my sleep is less productive too.
He has an appointment in about 6 weeks to see an ophthalmologist that specializes in neurological trauma/disease. Pray that she will be able to help David find a solution/ameliorate his vision. 
We are preparing for giving a presentation to over 100 apprentice lineman on safety, David's story, and our faith in the Lord Jesus. We may have a similar opportunity in the Fall with some PTA students in their neuro unit. Please pray for me as I will probably be doing most of the speaking, as David still has difficulty articulating his words clearly sometimes. For those who know me, I am NOT a public speaker nor do I ever like being front and center, especially in front of a 120 linemen!!! It will be about an hour presentation. God seems to be leading me to an uncomfortable place, a place where His strength can be made perfect through our weakness. That's exciting stuff, the thought that God can use an imperfect vessel like me and the broken body of my husband to further His kingdom and bring Himself glory. I want to learn more how to show forth his praises to His glory</p>

<p> 4/17/14 (Rachel Hanson)It's the small things that surprise me. The little things that come out of no where, normal things and expressions that David used to do that I haven't seen for almost 2 years now. Shoulder shrugs, bobbing his head in sync with music with a big grin on his face, his competitiveness in games...
We are busier than ever. David's bachelor pad is on the market. Taxes. YMCA. Horse therapy. Speaking engagements. Physical therapy has commenced again. Care giver problems continue. One evening last week, even though there was a crisis going on involving a care giver, we had family over for dinner and then the men were playing Rook and being silly at the table. It felt normal for once in a long, long time and David was so relaxed and calm that night. It was wonderful despite the bad circumstances going on.
I am really happy about David's new physical therapist. It is a man this time and for the first time (I think ever!) David was asking when he would get to go to PT again because he had fun. This PT seems motivated and energetic but compassionate, which is all of what David needs. He got him up in the parallel bars and had him working on standing/walking. Needless to say, David has a lot of work to do before he's actually walking, even in parallel bars, but he's up and he's working on it! We finally got the standing frame and have David standing in it almost every day.
David's mom is working with David on singing and being able to translate that into modulating his voice better. He is able to hit about 5 notes. He is able to emphasize words and modulate slightly...definitely better than a few months ago. 
David wants to work again and I think it would really help him to have some project or job or something that would give him a sense of responsibility and achievement once again. I'm still working on researching that area. It seems that most of the programs in our area are more catered toward people that have been handicapped their whole lives (mostly mentally) and I'm not sure it's an exact fit for David but he seemed excited about any opportunity to have a job so we'll see. Funding may be an issue too...not sure though.
We are so thankful for friends that have come by to visit us and for family that is so faithful in helping when we're in need.</p>
<p>

 <div id="fb-root"></div> <script>(function(d, s, id) { var js, fjs = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) return; js = d.createElement(s); js.id = id; js.src = "//connect.facebook.net/en_US/all.js#xfbml=1"; fjs.parentNode.insertBefore(js, fjs); }(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-post" data-href="https://www.facebook.com/photo.php?v=10151972481221193" data-width="466"><div class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/photo.php?v=10151972481221193">Post</a> by <a href="https://www.facebook.com/rachel.hanson86">Rachel Hanson</a>.</div></div>

<p> 5/16/14 (Rachel Hanson) 
This has been a big week for making appointments and going to appointments. The name of the game of brain injuries is WAIT, WAIT, and more Waiting! Time to heal, time to get in for important appointments, time to wait for important equipment... You name it, nothing happens immediately. We waited over a month to even get scheduled for a neuro psychology appointment, let alone see the whites of the man's eyes in August. Even more waiting for the endocrinologist...September is first available for him! We are finally getting some adaptive technology for David after waiting almost 3 months since his assessment.
 Yesterday, David went to a neuro ophthalmologist. She confirmed everyone's suspicions of optic nerve damage. He has no pupillary reflex in both eyes which means he is unable to control his depth of focus. This makes it impossible to see small print or anything far away and difficult to focus on large print. Although, this visit gave us bad news, it provided the opportunity for David and I to get away for a night all by ourselves! It was great! No care giver, no baby, just us!
 Today we went to David's physiatrist. He signed him up for occupational and speech therapy again. We also discussed a visit with the endocrinologist because of some behavioral and sleep problems that are possibly caused by hormonal imbalances. Unfortunately, there is only ONE very busy dude that does this specialty here! 
 Today was encouraging. David goes to ride horses and a man and his wife about our age work with him on the horse. David gave the guy one of his CDs last time and he made a point to talk to David about it today. He seems like a bright christian who loves the Lord. We rarely get such a bright response so it was so encouraging to talk to someone that seeks the Lord and loves Him.
 Things to pray for: sooner appointments with the neuro psychologist and endocrinologist, an improvement in sleep and insistant, disinhibited behavior, and spiritual encouragement/Christ-ward focus in our hearts.
</p>

<p> 5/24/14 (Rachel Hanson)
We are back at it again...PT, OT, ST and ET (equine therapy) plus WT (wifey therapy).  
 David does better and better at his walking. The left leg muscles are starting to kick in a little, at least his quads help straighten his leg a little. It's encouraging even though it's small steps...but in the right direction. You can see for yourself in the latest video. 
 I've noticed a few new things lately. David is doing better at being able to have a conversation where he can think about what the other person said a little more critically and comment from a previous memory that correlates with what the person said or add depth to the conversation. Tonight he was able to sing "When I Survey the Wondrous Cross" with his mom pretty much on tune and then surprised us with a real whistle when I asked him if he needed to "wet his whistle" after singing!
 Sleep is still an ongoing issue. But God is giving me more grace when I'm awakened to my husband sleep talking about his wild dreams at 3 am! Thank you for praying. 
 The Lord has been teaching me about the power of prayer lately. Admission: Sometimes I have secretly scoffed in my heart at those who ask for prayer for, it seems, every tiny little ailment or problem. But God has been teaching me that He delights in hearing our dumb little requests. His Word says, "Be anxious for nothing, but in EVERYTHING by prayer and supplication, with thanksgiving, let your requests be made known to God; and the peace of God, which surpasses all understanding, will guard your hearts and minds through Christ Jesus." Philippians 4:6,7 and "CONTINUE in prayer, and watch in the same with thanksgiving" Colossians 4:2 He delights in having the opportunity to change our hearts and lives. Prayer is the opportunity to give pieces of our life to Him, if not the whole, and see Him work His will. David and I were having a really rough night of sleeping (or lack thereof) a little while ago. I was getting really irritated because he was waking up about every 10 minutes from midnight to 5 am, insistently wanting to speak with me about dreams or plans for tomorrow or food he wanted... He was getting irritated at me because I wasn't wanting to listen to him. We went back and forth, the heat between us escalating until I went out on the couch. He just spoke louder and louder. I went back in and flipped the light on. I'd never seen so much anger in his eyes and he's probably never seen so much in mine! The look stopped me dead in my tracks...this wasn't about us, this was a power coming between us, trying to drive us away from each other and from the Lord. We decided to pray. Both of us had peace and calm and we slept after that. We are so slow to learn, the willingness to help and lovingkindness of God to creatures like us is so high.
<div id="fb-root"></div> <script>(function(d, s, id) { var js, fjs = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) return; js = d.createElement(s); js.id = id; js.src = "//connect.facebook.net/en_US/all.js#xfbml=1"; fjs.parentNode.insertBefore(js, fjs); }(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-post" data-href="https://www.facebook.com/photo.php?v=10152037168536193" data-width="466"><div class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/photo.php?v=10152037168536193">Post</a> by <a href="https://www.facebook.com/rachel.hanson86">Rachel Hanson</a>.</div></div>

<p> 6/19/14 (Rachel Hanson) David and I had the privilege of getting to celebrate our 2 year wedding anniversary together. It was much different and much better than last year! Last year David couldn't eat anything and was wiped out by just me wheeling him down the street to a coffee shop and little redwood grove and back. This year we got to watch a movie and go out to dinner.  God is good.
 David is getting better at scooping and getting his food to his mouth more independently. He is able to eat just about anything now, which is awesome for him and easier for me! He just had a swallow study that revealed his swallowing has improved so that he's only aspirating on 10% of thin liquids.
 David's therapists are great. They really try to motivate him by incorporating things into therapy that he enjoys. The speech therapist is using David's favorite game, Rook, to work on speech articulation and multitasking. He has to teach the therapist how to play the game and I have to bite my tongue the whole session to keep from automatically "interpreting" for him. I have gotten almost too good at interpreting his speech so, at home, he can get along with mushing along and slurring words together and I'll get it. 
 David's trunk control is coming along super slow but the PT is starting to make it a priority and we are integrating more at home. He got a few adaptive technology devices to make his computer more accessible. He is getting better at being able to type and open up emails, facebook, google searches, etc... with less help. He has a pair of funky glasses the OT is letting him borrow that have improved his vision so much that he could read the hymn book and read a story to Jocelyn for the first time since his accident!! The OT is also letting David drive in the driving simulator. David loves it!! Needless to say, he has lots of work to do before or if he ever drives again, but he does surprisingly well at braking for stop signs but needs work on staying on the road.  
 We are still in the process of finding something that works for David and I to get a full night of sleep.
 I will be posting some recent "media" of David's progress.</p>
</p>

<p> 7/1/14 (Rachel Hanson)
Maybe I'm a wimp but please pray for me. Last week, I had 5 whole shifts not covered by care givers and another one spent training a new one, which means I still pretty much did everything. My brain is just really overwhelmed right now. I got another message on my phone today that there are another 5 shifts open 5 days in a row. Thankfully I have help in the morning, so I guess I will be taking advantage of that as much as possible but we also have tons of appointments to attend the next few days too so that cuts time from them helping much at home. Also, thankfully, our little daughter is very well-behaved and makes life a lot easier than it could be. David is also less challenging to take care of than 10 months ago when we brought him home. There are lots of blessings. "I can do all things through Christ who strengthens me."  David and I quote this a lot. 
 On a positive note, I've noticed a brightening in David over the past few days. His speech is clearer and it seems a little more of the "fog" has lifted.  Even a lady at the hospital whom I've never noticed or talked to said today that she noticed David's face was brighter and more aware too. We tried taking him off a medication he's been on for awhile but he didn't do well off of it: severe headaches, irritability, weakness, etc... so he's back on it and we've seen a lot of benefit, so I guess he does need that drug.  David is getting better and better at initiating realistic short-term plans like trips and outings without any prompting from me.
 One thing I'm so thankful for is David's spirit through all of this. A couple nights ago, he looked at me and said, "These are the best days of my life!" and told his psychologist today that he's a very happy man. It makes my heart sing to hear him say these things. I'm so grateful for a man that triumphs over trial with joy and prays so often for us to be satisfied with God's will for us.
</p>

<p>7/11/14 (Rachel Hanson)
Thank you for praying for me. One of my care givers worked overtime a lot and my brother-in-law helped out too. 
 One of the things that is always pushing at us is progress. Insurance doesn't like to pay for continued therapy if there isn't measurable progress. David's brain injury was very severe and even though we are pushing him constantly, it takes lots of time to rewire and reroute around all the damaged areas. The more I read anecdotal cases of brain injuries like David's, I am amazed at what miracles the Lord has done for us. I need to work on a list of things that have improved over the last month or so to prepare for a meeting between the therapists, doctor and insurance case manager and us. The therapists have better eyes than the doctor because they see more of David but I have the best eyes because I see all the little things at home and at therapy. Here's things I have noticed lately:
 - He demonstrated righting reaction for the first time in sitting by putting out his right arm to catch himself when he was falling to the right.
 - He can bring his trunk upright again after flopping to the left when I turn a corner while driving without cuing
 - He can sit unassisted on the edge of the bed for 1 minute (slouchy still)
 - He can feed 75% of his meal to himself without assistance
 - He can drink with supervision
 - He can shave about 60% of his face
 - He can help with washing himself in the shower
 - He can lean forward in his wheelchair with very little assistance
 - He can balance in standing with me just placing two hands lightly on his pelvis
 - He can weight shift through his hips while holding onto a bar without sagging
 - He can check his email and facebook independently, plus do google searches
 - His working memory seems to be improving some, as he is able to recall and understand the plot and gist of a 2 hour movie
 I don't know if you know how hard David works every day but I'll give you a sample. Sometimes he has three hours of therapy in one day and then he does over an hour of exercises before 11pm. Most days he doesn't get to sleep before midnight. He works out at the YMCA a couple times a week for almost 2 hours. Everything has to be repeated a thousand times, it seems, to be able to make a functional gain.
 Tonight we got to enjoy a date together without baby. Sometimes his quick wit catches me off guard because it is so unexpected. We went to a restaurant and when the waiter delivered our food, he said something like, "Enjoy". I said, "You too." David started laughing at me and said, "He didn't get anything." Oh. I'm a dumdum. lol</p>

<p>8/20/14 (Rachel Hanson)
We were able to enjoy a wonderful week at a Christian camp last week. I had lots of help from the Hanson family in making it possible for us. It's so unbelievably wonderful to be surrounded by Christians and awesome ministry for a whole week! It was challenging but still enjoyable and I was able to sneak away by myself a couple times to relax kayaking around the lake. David surprised us by stepping up 2-1/2 steps up to the sauna with my help! He used to love the sauna ...and was so determined to get up in that sauna that he did the unthinkable! Unfortunately there were more than 2 steps...so maybe next year.
Please pray for us in the next couple months as to some big decision-making. We had a family/therapist/doctor meeting today. Some big things came up in the meeting. David has made a lot of progress but I think we are of one mind that his therapy needs to stepped up to see if we can speed up his progress. The thinking is to have him spend a few months in an intensive inpatient rehab setting a couple hours away from our home. David is surprisingly willing to do this. We are, Lord willing, planning a trip to California in about a month. Please pray that the Lord would either expedite the process of getting his new, smaller, lighter wheelchair before the trip or provide a chair to rent or something. Pray also about details to be worked out with David's insurance funding. I think it should be ok but the two-year "temporary disability" status is over and needs to be changed to a percentage of permanent disability to determine funding. Pray that there would be an appointment opening in the time frame that we're in CA so David can be seen by the "medical examiner".
"For this God is our God for ever and ever: he will be our guide even unto death." Psalms 48:14</p>

<p> 8/29/14 (Rachel Hanson)

Just a little update: two of my prayer requests have been answered...we got a trial wheelchair that the wheelchair company is letting us use for free on our trip to CA and the medical examiner doctor was able to shuffle things around and squeeze David in during our stay in CA. I love when God answers specific prayer requests!
"LORD, what is man, that You take knowledge of him?
Or the son of man, that You are mindful of him?" Psalms 144:3
“Are not two sparrows sold for a copper coin? And not one of them falls to the ground apart from your Father’s will. But the very hairs of your head are all numbered. Do not fear therefore; you are of more value than many sparrows." Matthew 10:29-31</p>

<p>9/4/14 (Rachel Hanson)

We got two pieces of news today that kind of made my heart sink a bit. We went over David's psychometric testing results. They were not good. It doesn't really change what we do, it just spells out what we've been seeing lately, in black and white. I find myself fearing when David stops making progress, the point when we just live with what is. There's a certain comfort in the forward progress, but it becomes my hope ("something better around the corner"), a greed of hea...rt, a discontentment of the circumstances of here and now. The testing was limited and probably not 100% accurate because of the way we had to do it because of David's speech deficits, but there was also a lot of truth in the assessment. David didn't want to know the results at first and wanted me to speak privately with the doctor but later he was overcome with curiosity and had to know. He was very quiet after hearing the results. It's disheartening but I reassured him he's come so far, especially in the last year and he is still progressing. It's just test results, it doesn't have to dictate our lives or change how I see my husband.
The second piece of news is that David is not a candidate for the intensive rehab facility. I guess we are doing too good of a job here at home. Since he is doing a good job reintegrating back into the community and still making progress with seeing his therapists a couple times a week, they somehow can't justify the intensive rehab. In a way, it's a relief, but I'll always wonder what he could have done with that opportunity. I have to trust that this is God's will for us and it is good.
"Now godliness with contentment is great gain. For we brought nothing into this world, and it is certain we can carry nothing out. And having food and clothing, with these we shall be content. But those who desire to be rich fall into temptation and a snare, and into many foolish and harmful lusts which drown men in destruction and perdition. For the love of money is a root of all kinds of evil, for which some have strayed from the faith in their greediness, and pierced themselves through with many sorrows. But you, O man of God, flee these things and pursue righteousness, godliness, faith, love, patience, gentleness. Fight the good fight of faith, lay hold on eternal life, to which you were also called and have confessed the good confession in the presence of many witnesses." I Timothy 6:6-12
I am challenged by these verses in my lack of contentment. It's not riches I seek, but a whole husband that leads. But I see evidence of God's work in him to begin to lead and it's beautiful to see! </p>

<p> 9/7/14 (Rachel Hanson)
One of the most important things or maybe I should say moments in the world to David is to remember the Lord. He loves unity among Christians in this moment, to show forth the Lord's death until He comes. Last Sunday, he shared John 10:10b ("I have come that they may have life, and that they may have it more abundantly.") and this Sunday, he turned to me and whispered, "Can I pray?" I whispered back, "Go ahead!" He prayed a beautiful prayer thankful for the Lord being broken for us.
<img src="img/feedingjocelyn.jpg" width="400" height="225" align="Left" border="1"> I'm also sharing a photo of David and Jocelyn. He loves sharing treats with her (ie. spoiling ) and she loves that he shares treats with her!! He loves taking opportunities to win her affection. It's fun to see the connection between the two.</p>

<p>10/8/14 (Rachel Hanson)
A lot of people ask how I'm doing...accompanied by a look that says they want more than just the, "Good, how are you?" When you go through something like this, it touches deep places in a soul that make it difficult to put into words what goes through my head and heart in a quick conversation. It's like I'm married to two different men in one body...the new David and the old David. I've found it almost impossible to grieve this loss that's an incomplete loss because life trundles on and if I don't want to miss the train, I better get on board. I love being married. I love having purpose and having the gift of loving my husband and daughter. I love being able to cook to my heart's content and spoil my husband's palate. I love being able to see God's healing handiwork in my husband's body in slow motion. I love being given the opportunity to research a medical topic to the wee hours of the morning just to see if I can find something more to give more quality of life to my husband. I love that I have been gifted with a supportive, loving, godly family on both sides.
I struggle with bitterness and anger and deep hurt. I get overwhelmed emotionally by the mental toll this life takes. My brain shuts down and all I want to do is sleep or have absolute quiet.
That's it. That's the convoluted, messy answer to how I am doing.<br>

On a note about David, he is starting to step with his left leg!!! We are hitting the walking goal harder than anything else right now. We have a walking device at home that has a butterfly-shaped sling that goes in between his legs and attaches to the trunk support so if his legs buckle, there are no mishaps. ? He walks about 20 feet twice 6 days a week and then once or twice at PT. Please pray for David's mind to be stayed on Christ and to initiate healthy activities.</p>

<p> 10/20/14 (Rachel Hanson)
<img src="img/davidatpark.jpg" width="612" height="408" align="Right" border="1">We have had a really good week, consummated by a great weekend. On Saturday, we had a beautiful, sunny fall day so we took advantage of it and went to a park. Jocelyn got to swing and David got to throw a frisbee. Then we went home and made cookies. Sunday, we went to church and went bowling and out to eat with family. It almost felt normal this weekend.
</p>

<p>For the most current news to date visit: <a href="http://thecerebralclimb.blogspot.com/" target="_blank" >2014 </a> ~ The Cerebral Climb Blog by Rachel Hanson</p>

<table width="100%" border="0" cellspacing="5" class="boxText">


<?php include("inc/footer.inc.php"); ?>

</body>
</html>
